version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/usr/src/app/client  # Bind mount for source code
      - /usr/src/app/client/node_modules  # Preserve node_modules inside the container
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - app_network

  db:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  adminer_mongo:
    image: dockette/adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8081
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge