version: "3"
services:
  api:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - ./server/config/.env
    depends_on:
      - mongo

  web:
    build: ./client
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    links:
      - api
      - web

  mongo:
    image: bitnami/mongodb:7.0.9-debian-12-r4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
