version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_app
    ports:
      - "3000:80"  # Map container port 80 (Nginx serving frontend) to localhost:3000
    networks:
      - app_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_app
    ports:
      - "5001:5001"  # Map container port 5001 to localhost:5001
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "80:80"  # Map Nginx container port 80 to localhost (http://localhost)
    depends_on:
      - client
      - server
    networks:
      - app_network

  db:
    image: mongo:6
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  adminer_mongo:
    image: dockette/adminer
    restart: always
    ports:
      - "8087:80" 
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge