apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app # This should match the label of your app pod
  ports:
    - port: 80 # Port that will be exposed outside the cluster
      targetPort: 3000 # Port your app is listening on inside the pod
  type: ClusterIP # Use LoadBalancer or NodePort for external access
