apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: default # Adjust this to the namespace where Grafana is running, if necessary.
data:
  grafana-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:9090
        isDefault: true
