pipeline {
    agent any
    stages {
        stage('Check Docker Path') {
            steps {
                sh 'echo $PATH'
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker build -t myapp:${BUILD_NUMBER} .'
            }
        }
        stage('Scan') {
            steps {
                sh 'trivy image myapp:${BUILD_NUMBER}'
            }
        }
        stage('Push') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker tag myapp:${BUILD_NUMBER} bilelsalemdev/myapp:${BUILD_NUMBER}'
                    sh 'docker push bilelsalemdev/myapp:${BUILD_NUMBER}'
                }
            }
        }
    }
}
